// AUTOGENERATED BY LIBBPF-GO-GEN
// DO NOT EDIT
package libbpf

// #include <bpf/btf.h>
import "C"
import "unsafe"

var _ unsafe.Pointer

// Btf__free is a wrapper of btf__free
//     void btf__free(struct btf *btf)
func Btf__free(btf *Struct_btf)  {
	return C.btf__free()
}

// Btf__new is a wrapper of btf__new
//     struct btf *btf__new(const void *data, __u32 size)
func Btf__new(data unsafe.Pointer, size uint32) *Struct_btf {
	return C.btf__new()
}

// Btf__new_split is a wrapper of btf__new_split
//     struct btf *btf__new_split(const void *data, __u32 size, struct btf *base_btf)
func Btf__new_split(data unsafe.Pointer, size uint32, base_btf *Struct_btf) *Struct_btf {
	return C.btf__new_split()
}

// Btf__new_empty is a wrapper of btf__new_empty
//     struct btf *btf__new_empty(void)
func Btf__new_empty( ) *Struct_btf {
	return C.btf__new_empty()
}

// Btf__new_empty_split is a wrapper of btf__new_empty_split
//     struct btf *btf__new_empty_split(struct btf *base_btf)
func Btf__new_empty_split(base_btf *Struct_btf) *Struct_btf {
	return C.btf__new_empty_split()
}

// Btf__parse is a wrapper of btf__parse
//     struct btf *btf__parse(const char *path, struct btf_ext **btf_ext)
func Btf__parse(path string, btf_ext *Struct_btf_ext) *Struct_btf {
	return C.btf__parse()
}

// Btf__parse_split is a wrapper of btf__parse_split
//     struct btf *btf__parse_split(const char *path, struct btf *base_btf)
func Btf__parse_split(path string, base_btf *Struct_btf) *Struct_btf {
	return C.btf__parse_split()
}

// Btf__parse_elf is a wrapper of btf__parse_elf
//     struct btf *btf__parse_elf(const char *path, struct btf_ext **btf_ext)
func Btf__parse_elf(path string, btf_ext *Struct_btf_ext) *Struct_btf {
	return C.btf__parse_elf()
}

// Btf__parse_elf_split is a wrapper of btf__parse_elf_split
//     struct btf *btf__parse_elf_split(const char *path, struct btf *base_btf)
func Btf__parse_elf_split(path string, base_btf *Struct_btf) *Struct_btf {
	return C.btf__parse_elf_split()
}

// Btf__parse_raw is a wrapper of btf__parse_raw
//     struct btf *btf__parse_raw(const char *path)
func Btf__parse_raw(path string) *Struct_btf {
	return C.btf__parse_raw()
}

// Btf__parse_raw_split is a wrapper of btf__parse_raw_split
//     struct btf *btf__parse_raw_split(const char *path, struct btf *base_btf)
func Btf__parse_raw_split(path string, base_btf *Struct_btf) *Struct_btf {
	return C.btf__parse_raw_split()
}

// Btf__finalize_data is a wrapper of btf__finalize_data
//     int btf__finalize_data(struct bpf_object *obj, struct btf *btf)
func Btf__finalize_data(obj *Struct_bpf_object, btf *Struct_btf) int32 {
	return C.btf__finalize_data()
}

// Btf__load is a wrapper of btf__load
//     int btf__load(struct btf *btf)
func Btf__load(btf *Struct_btf) int32 {
	return C.btf__load()
}

// Btf__find_by_name is a wrapper of btf__find_by_name
//     __s32 btf__find_by_name(const struct btf *btf, const char *type_name)
func Btf__find_by_name(btf *Struct_btf, type_name string) int32 {
	return C.btf__find_by_name()
}

// Btf__find_by_name_kind is a wrapper of btf__find_by_name_kind
//     __s32 btf__find_by_name_kind(const struct btf *btf, const char *type_name, __u32 kind)
func Btf__find_by_name_kind(btf *Struct_btf, type_name string, kind uint32) int32 {
	return C.btf__find_by_name_kind()
}

// Btf__get_nr_types is a wrapper of btf__get_nr_types
//     __u32 btf__get_nr_types(const struct btf *btf)
func Btf__get_nr_types(btf *Struct_btf) uint32 {
	return C.btf__get_nr_types()
}

// Btf__base_btf is a wrapper of btf__base_btf
//     const struct btf *btf__base_btf(const struct btf *btf)
func Btf__base_btf(btf *Struct_btf) *Struct_btf {
	return C.btf__base_btf()
}

// Btf__type_by_id is a wrapper of btf__type_by_id
//     const struct btf_type *btf__type_by_id(const struct btf *btf, __u32 id)
func Btf__type_by_id(btf *Struct_btf, id uint32) *Struct_btf_type {
	return C.btf__type_by_id()
}

// Btf__pointer_size is a wrapper of btf__pointer_size
//     size_t btf__pointer_size(const struct btf *btf)
func Btf__pointer_size(btf *Struct_btf) uint {
	return C.btf__pointer_size()
}

// Btf__set_pointer_size is a wrapper of btf__set_pointer_size
//     int btf__set_pointer_size(struct btf *btf, size_t ptr_sz)
func Btf__set_pointer_size(btf *Struct_btf, ptr_sz uint) int32 {
	return C.btf__set_pointer_size()
}

// Btf__endianness is a wrapper of btf__endianness
//     enum btf_endianness btf__endianness(const struct btf *btf)
func Btf__endianness(btf *Struct_btf) Enum_btf_endianness {
	return C.btf__endianness()
}

// Btf__set_endianness is a wrapper of btf__set_endianness
//     int btf__set_endianness(struct btf *btf, enum btf_endianness endian)
func Btf__set_endianness(btf *Struct_btf, endian Enum_btf_endianness) int32 {
	return C.btf__set_endianness()
}

// Btf__resolve_size is a wrapper of btf__resolve_size
//     __s64 btf__resolve_size(const struct btf *btf, __u32 type_id)
func Btf__resolve_size(btf *Struct_btf, type_id uint32) int64 {
	return C.btf__resolve_size()
}

// Btf__resolve_type is a wrapper of btf__resolve_type
//     int btf__resolve_type(const struct btf *btf, __u32 type_id)
func Btf__resolve_type(btf *Struct_btf, type_id uint32) int32 {
	return C.btf__resolve_type()
}

// Btf__align_of is a wrapper of btf__align_of
//     int btf__align_of(const struct btf *btf, __u32 id)
func Btf__align_of(btf *Struct_btf, id uint32) int32 {
	return C.btf__align_of()
}

// Btf__fd is a wrapper of btf__fd
//     int btf__fd(const struct btf *btf)
func Btf__fd(btf *Struct_btf) int32 {
	return C.btf__fd()
}

// Btf__set_fd is a wrapper of btf__set_fd
//     void btf__set_fd(struct btf *btf, int fd)
func Btf__set_fd(btf *Struct_btf, fd int32)  {
	return C.btf__set_fd()
}

// Btf__get_raw_data is a wrapper of btf__get_raw_data
//     const void *btf__get_raw_data(const struct btf *btf, __u32 *size)
func Btf__get_raw_data(btf *Struct_btf, size *uint32) unsafe.Pointer {
	return C.btf__get_raw_data()
}

// Btf__name_by_offset is a wrapper of btf__name_by_offset
//     const char *btf__name_by_offset(const struct btf *btf, __u32 offset)
func Btf__name_by_offset(btf *Struct_btf, offset uint32) string {
	return C.btf__name_by_offset()
}

// Btf__str_by_offset is a wrapper of btf__str_by_offset
//     const char *btf__str_by_offset(const struct btf *btf, __u32 offset)
func Btf__str_by_offset(btf *Struct_btf, offset uint32) string {
	return C.btf__str_by_offset()
}

// Btf__get_from_id is a wrapper of btf__get_from_id
//     int btf__get_from_id(__u32 id, struct btf **btf)
func Btf__get_from_id(id uint32, btf *Struct_btf) int32 {
	return C.btf__get_from_id()
}

// Btf__get_map_kv_tids is a wrapper of btf__get_map_kv_tids
//     int btf__get_map_kv_tids(const struct btf *btf, const char *map_name, __u32 expected_key_size, __u32 expected_value_size, __u32 *key_type_id, __u32 *value_type_id)
func Btf__get_map_kv_tids(btf *Struct_btf, map_name string, expected_key_size uint32, expected_value_size uint32, key_type_id *uint32, value_type_id *uint32) int32 {
	return C.btf__get_map_kv_tids()
}

// Btf_ext__new is a wrapper of btf_ext__new
//     struct btf_ext *btf_ext__new(__u8 *data, __u32 size)
func Btf_ext__new(data *uint8, size uint32) *Struct_btf_ext {
	return C.btf_ext__new()
}

// Btf_ext__free is a wrapper of btf_ext__free
//     void btf_ext__free(struct btf_ext *btf_ext)
func Btf_ext__free(btf_ext *Struct_btf_ext)  {
	return C.btf_ext__free()
}

// Btf_ext__get_raw_data is a wrapper of btf_ext__get_raw_data
//     const void *btf_ext__get_raw_data(const struct btf_ext *btf_ext, __u32 *size)
func Btf_ext__get_raw_data(btf_ext *Struct_btf_ext, size *uint32) unsafe.Pointer {
	return C.btf_ext__get_raw_data()
}

// Btf_ext__reloc_func_info is a wrapper of btf_ext__reloc_func_info
//      int btf_ext__reloc_func_info(const struct btf *btf, const struct btf_ext *btf_ext, const char *sec_name, __u32 insns_cnt, void **func_info, __u32 *cnt)
func Btf_ext__reloc_func_info(btf *Struct_btf, btf_ext *Struct_btf_ext, sec_name string, insns_cnt uint32, func_info unsafe.Pointer, cnt *uint32) int32 {
	return C.btf_ext__reloc_func_info()
}

// Btf_ext__reloc_line_info is a wrapper of btf_ext__reloc_line_info
//      int btf_ext__reloc_line_info(const struct btf *btf, const struct btf_ext *btf_ext, const char *sec_name, __u32 insns_cnt, void **line_info, __u32 *cnt)
func Btf_ext__reloc_line_info(btf *Struct_btf, btf_ext *Struct_btf_ext, sec_name string, insns_cnt uint32, line_info unsafe.Pointer, cnt *uint32) int32 {
	return C.btf_ext__reloc_line_info()
}

// Btf_ext__func_info_rec_size is a wrapper of btf_ext__func_info_rec_size
//     __u32 btf_ext__func_info_rec_size(const struct btf_ext *btf_ext)
func Btf_ext__func_info_rec_size(btf_ext *Struct_btf_ext) uint32 {
	return C.btf_ext__func_info_rec_size()
}

// Btf_ext__line_info_rec_size is a wrapper of btf_ext__line_info_rec_size
//     __u32 btf_ext__line_info_rec_size(const struct btf_ext *btf_ext)
func Btf_ext__line_info_rec_size(btf_ext *Struct_btf_ext) uint32 {
	return C.btf_ext__line_info_rec_size()
}

// Libbpf_find_kernel_btf is a wrapper of libbpf_find_kernel_btf
//     struct btf *libbpf_find_kernel_btf(void)
func Libbpf_find_kernel_btf( ) *Struct_btf {
	return C.libbpf_find_kernel_btf()
}

// Btf__find_str is a wrapper of btf__find_str
//     int btf__find_str(struct btf *btf, const char *s)
func Btf__find_str(btf *Struct_btf, s string) int32 {
	return C.btf__find_str()
}

// Btf__add_str is a wrapper of btf__add_str
//     int btf__add_str(struct btf *btf, const char *s)
func Btf__add_str(btf *Struct_btf, s string) int32 {
	return C.btf__add_str()
}

// Btf__add_type is a wrapper of btf__add_type
//     int btf__add_type(struct btf *btf, const struct btf *src_btf, const struct btf_type *src_type)
func Btf__add_type(btf *Struct_btf, src_btf *Struct_btf, src_type *Struct_btf_type) int32 {
	return C.btf__add_type()
}

// Btf__add_int is a wrapper of btf__add_int
//     int btf__add_int(struct btf *btf, const char *name, size_t byte_sz, int encoding)
func Btf__add_int(btf *Struct_btf, name string, byte_sz uint, encoding int32) int32 {
	return C.btf__add_int()
}

// Btf__add_float is a wrapper of btf__add_float
//     int btf__add_float(struct btf *btf, const char *name, size_t byte_sz)
func Btf__add_float(btf *Struct_btf, name string, byte_sz uint) int32 {
	return C.btf__add_float()
}

// Btf__add_ptr is a wrapper of btf__add_ptr
//     int btf__add_ptr(struct btf *btf, int ref_type_id)
func Btf__add_ptr(btf *Struct_btf, ref_type_id int32) int32 {
	return C.btf__add_ptr()
}

// Btf__add_array is a wrapper of btf__add_array
//     int btf__add_array(struct btf *btf, int index_type_id, int elem_type_id, __u32 nr_elems)
func Btf__add_array(btf *Struct_btf, index_type_id int32, elem_type_id int32, nr_elems uint32) int32 {
	return C.btf__add_array()
}

// Btf__add_struct is a wrapper of btf__add_struct
//     int btf__add_struct(struct btf *btf, const char *name, __u32 sz)
func Btf__add_struct(btf *Struct_btf, name string, sz uint32) int32 {
	return C.btf__add_struct()
}

// Btf__add_union is a wrapper of btf__add_union
//     int btf__add_union(struct btf *btf, const char *name, __u32 sz)
func Btf__add_union(btf *Struct_btf, name string, sz uint32) int32 {
	return C.btf__add_union()
}

// Btf__add_field is a wrapper of btf__add_field
//     int btf__add_field(struct btf *btf, const char *name, int field_type_id, __u32 bit_offset, __u32 bit_size)
func Btf__add_field(btf *Struct_btf, name string, field_type_id int32, bit_offset uint32, bit_size uint32) int32 {
	return C.btf__add_field()
}

// Btf__add_enum is a wrapper of btf__add_enum
//     int btf__add_enum(struct btf *btf, const char *name, __u32 bytes_sz)
func Btf__add_enum(btf *Struct_btf, name string, bytes_sz uint32) int32 {
	return C.btf__add_enum()
}

// Btf__add_enum_value is a wrapper of btf__add_enum_value
//     int btf__add_enum_value(struct btf *btf, const char *name, __s64 value)
func Btf__add_enum_value(btf *Struct_btf, name string, value int64) int32 {
	return C.btf__add_enum_value()
}

// Btf__add_fwd is a wrapper of btf__add_fwd
//     int btf__add_fwd(struct btf *btf, const char *name, enum btf_fwd_kind fwd_kind)
func Btf__add_fwd(btf *Struct_btf, name string, fwd_kind Enum_btf_fwd_kind) int32 {
	return C.btf__add_fwd()
}

// Btf__add_typedef is a wrapper of btf__add_typedef
//     int btf__add_typedef(struct btf *btf, const char *name, int ref_type_id)
func Btf__add_typedef(btf *Struct_btf, name string, ref_type_id int32) int32 {
	return C.btf__add_typedef()
}

// Btf__add_volatile is a wrapper of btf__add_volatile
//     int btf__add_volatile(struct btf *btf, int ref_type_id)
func Btf__add_volatile(btf *Struct_btf, ref_type_id int32) int32 {
	return C.btf__add_volatile()
}

// Btf__add_const is a wrapper of btf__add_const
//     int btf__add_const(struct btf *btf, int ref_type_id)
func Btf__add_const(btf *Struct_btf, ref_type_id int32) int32 {
	return C.btf__add_const()
}

// Btf__add_restrict is a wrapper of btf__add_restrict
//     int btf__add_restrict(struct btf *btf, int ref_type_id)
func Btf__add_restrict(btf *Struct_btf, ref_type_id int32) int32 {
	return C.btf__add_restrict()
}

// Btf__add_func is a wrapper of btf__add_func
//     int btf__add_func(struct btf *btf, const char *name, enum btf_func_linkage linkage, int proto_type_id)
func Btf__add_func(btf *Struct_btf, name string, linkage Enum_btf_func_linkage, proto_type_id int32) int32 {
	return C.btf__add_func()
}

// Btf__add_func_proto is a wrapper of btf__add_func_proto
//     int btf__add_func_proto(struct btf *btf, int ret_type_id)
func Btf__add_func_proto(btf *Struct_btf, ret_type_id int32) int32 {
	return C.btf__add_func_proto()
}

// Btf__add_func_param is a wrapper of btf__add_func_param
//     int btf__add_func_param(struct btf *btf, const char *name, int type_id)
func Btf__add_func_param(btf *Struct_btf, name string, type_id int32) int32 {
	return C.btf__add_func_param()
}

// Btf__add_var is a wrapper of btf__add_var
//     int btf__add_var(struct btf *btf, const char *name, int linkage, int type_id)
func Btf__add_var(btf *Struct_btf, name string, linkage int32, type_id int32) int32 {
	return C.btf__add_var()
}

// Btf__add_datasec is a wrapper of btf__add_datasec
//     int btf__add_datasec(struct btf *btf, const char *name, __u32 byte_sz)
func Btf__add_datasec(btf *Struct_btf, name string, byte_sz uint32) int32 {
	return C.btf__add_datasec()
}

// Btf__add_datasec_var_info is a wrapper of btf__add_datasec_var_info
//     int btf__add_datasec_var_info(struct btf *btf, int var_type_id, __u32 offset, __u32 byte_sz)
func Btf__add_datasec_var_info(btf *Struct_btf, var_type_id int32, offset uint32, byte_sz uint32) int32 {
	return C.btf__add_datasec_var_info()
}

// Btf__dedup is a wrapper of btf__dedup
//     int btf__dedup(struct btf *btf, struct btf_ext *btf_ext, const struct btf_dedup_opts *opts)
func Btf__dedup(btf *Struct_btf, btf_ext *Struct_btf_ext, opts *Struct_btf_dedup_opts) int32 {
	return C.btf__dedup()
}

// Btf_dump__new is a wrapper of btf_dump__new
//     struct btf_dump *btf_dump__new(const struct btf *btf, const struct btf_ext *btf_ext, const struct btf_dump_opts *opts, btf_dump_printf_fn_t printf_fn)
func Btf_dump__new(btf *Struct_btf, btf_ext *Struct_btf_ext, opts *Struct_btf_dump_opts, printf_fn C.btf_dump_printf_fn_t) *Struct_btf_dump {
	return C.btf_dump__new()
}

// Btf_dump__free is a wrapper of btf_dump__free
//     void btf_dump__free(struct btf_dump *d)
func Btf_dump__free(d *Struct_btf_dump)  {
	return C.btf_dump__free()
}

// Btf_dump__dump_type is a wrapper of btf_dump__dump_type
//     int btf_dump__dump_type(struct btf_dump *d, __u32 id)
func Btf_dump__dump_type(d *Struct_btf_dump, id uint32) int32 {
	return C.btf_dump__dump_type()
}

// Btf_dump__emit_type_decl is a wrapper of btf_dump__emit_type_decl
//     int btf_dump__emit_type_decl(struct btf_dump *d, __u32 id, const struct btf_dump_emit_type_decl_opts *opts)
func Btf_dump__emit_type_decl(d *Struct_btf_dump, id uint32, opts *Struct_btf_dump_emit_type_decl_opts) int32 {
	return C.btf_dump__emit_type_decl()
}
